# Generated by Django 5.0.1 on 2024-01-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_employee_team_remove_employeeprofile_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.team'),
        ),
    ]
